### PR TITLE
Fix optional field validation and nested combo defaults, and regenerate artifacts

### LINKED ISSUE #4594: [Ballerina][MI] Nested Union Combo Fields Pollute XML with Unused Default Values
### Description

When a union type contains another union type as a member (nested unions), the nested combo fields are assigned default values. This causes MI Designer to save these unused default values to the `init.xml` configuration file, even when the parent union member is not selected.

This results in:
- Verbose and cluttered XML configuration files
- Potentially confusing configuration with values for unselected union members
- Incorrect state being persisted in the connector configuration

The issue occurs in `ConnectorSerializer.java` where default values are calculated for combo fields without considering whether the combo is a top-level or nested field.

### Steps to Reproduce

1. Create a Ballerina connector with a union type containing another union type:

   ```ballerina
   public type AuthConfig record {|
       BearerTokenConfig|OAuth2Config auth;
   |};
   
   public type OAuth2Config record {|
       ClientCredentialsConfig|RefreshTokenConfig clientAuth;
       string tokenUrl;
   |};
   
   public type BearerTokenConfig record {|
       string token;
   |};
   
   public type ClientCredentialsConfig record {|
       string clientId;
       string clientSecret;
   |};
   
   public type RefreshTokenConfig record {|
       string refreshToken;
       string clientId;
       string clientSecret;
   |};
   ```

2. Generate the MI module artifacts using the `bal mi-gen` tool.

3. Open the generated connector in MI Designer.

4. Select `BearerTokenConfig` as the authentication type (first-level union).

5. Fill in the `token` field and save the configuration.

6. **Expected Result:** Only `BearerTokenConfig` related properties should be saved to `init.xml`.

7. **Actual Result:** The `init.xml` also contains default values for the nested `clientAuth` combo field (e.g., `ClientCredentialsConfig`) even though `OAuth2Config` was not selected, polluting the configuration with unused values.

### Version

latest

### Environment Details (with versions)

_No response_

### LINKED ISSUE #4595: [Ballerina][MI] Regex Validation Applied to Optional Fields in UI Schema
### Description

Optional fields (`INT`, `DECIMAL`, `FLOAT`, `JSON`, `RECORD` types) are incorrectly assigned regex validation patterns in the generated UI schema. This causes validation failures when the user leaves an optional field empty, as the regex pattern expects a specific value format (e.g., integer, decimal, JSON object) instead of allowing an empty string.

The issue occurs in `ConnectorSerializer.java` where regex validation is unconditionally applied to all fields regardless of their `required` status. Optional fields should allow empty values without triggering validation errors.

**Affected field types:**
- `INT` - Integer regex pattern applied to optional fields
- `DECIMAL` / `FLOAT` - Decimal regex pattern applied to optional fields  
- `JSON` - JSON object regex pattern applied to optional fields
- `RECORD` - JSON object regex pattern applied to optional record fields

### Steps to Reproduce

1. Create a Ballerina connector with an optional parameter of type `int`, `decimal`, `float`, or a record type.

   ```ballerina
   public function createResource(int? optionalCount, record { string name; }? optionalConfig) returns error? {
       // ...
   }
   ```

2. Generate the MI module artifacts using the `bal mi-gen` tool.

3. Open the generated connector in MI Designer.

4. Leave the optional field empty and attempt to save the configuration.

5. **Expected Result:** The configuration should save successfully since the field is optional.

6. **Actual Result:** Validation error occurs because the empty value doesn't match the regex pattern (e.g., `^[-+]?[0-9]+$` for integers or `^\s*\{[\s\S]*\}\s*$` for JSON objects).

### Version

latest

### Environment Details (with versions)

_No response_

### PR DESCRIPTION
**Pull request by iamvirul**
## Purpose

Fix validation issues in the generated UI schema where:
1. Fix: https://github.com/wso2/product-micro-integrator/issues/4595
2. Fix: https://github.com/wso2/product-micro-integrator/issues/4594

## Goals

- Ensure optional fields (`INT`, `DECIMAL`, `FLOAT`, `JSON`, `RECORD` types) accept empty values without triggering validation errors
- Prevent nested combo fields from polluting XML configuration with unused default values
- Improve debugging visibility with enhanced logging for record value creation

### 1. Conditional Regex Validation for Optional Fields
Modified `ConnectorSerializer.java` to only apply regex validation (`validateType` and `matchPattern`) for **required** fields. Optional fields will have empty validation patterns, allowing them to accept empty values.

**Affected cases:**
- `JSON` type parameters
- `RECORD` type parameters  
- `INT` type parameters
- `DECIMAL`/`FLOAT` type parameters

### 2. Smart Default Values for Nested Combos
Updated the `getCombo()` method in `ConnectorSerializer.java` to check if the combo field has an `enableCondition`. If present (indicating it's a nested combo), the default value is set to empty string instead of the first union member. This prevents MI Designer from saving unused defaults to the XML configuration.

### 3. Enhanced Logging in BalExecutor
Added prominent logging in `BalExecutor.java` to display:
- Final JSON being passed to Ballerina runtime
- Typed record after `FromJsonStringWithType` conversion (showing applied defaults)

## User stories

As a user creating connectors with optional parameters, I want to leave optional fields empty without encountering validation errors in MI Designer.

As a user working with union types, I want the `init.xml` to only contain values for the union member I selected, without pollution from nested union defaults.

## Release note

- Fixed: Optional fields no longer fail validation when left empty in MI Designer
- Fixed: Nested union combo fields no longer pollute XML configuration with unused default values

## Documentation

N/A - Internal bug fix that doesn't change public API or user-facing behavior beyond fixing incorrect validation.

## Training

N/A

## Certification

N/A - Bug fix only.

## Marketing

N/A

## Automation tests

- Unit tests
  > Existing test coverage validates the fix. No new test cases required as this is a behavioral fix for existing functionality.
- Integration tests
  > Manual verification with connectors containing optional parameters and nested union types.

## Security checks

- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples

N/A

## Related PRs

N/A

## Migrations (if applicable)

N/A - No migration required.

## Test environment

- JDK: 17
- Operating System: macOS

## Learning

N/A

### CODE REVIEW

File: native/src/main/java/io/ballerina/stdlib/mi/BalExecutor.java [hunk 1]
```diff
@@ -502,10 +502,33 @@ private Object createRecordValue(String jsonString, String paramName, MessageCon
...
-                log.info("DEBUG: Converting BMap to typed record. JSON string: " + jsonStr);
+                
+                // ======== PROMINENT LOGGING: Final JSON being passed to Ballerina ========
+                log.info("╔═══════════════════════════════════════════════════════════════════════════════");
+                log.info("║ FINAL CONNECTION CONFIG JSON FOR BALLERINA");
+                log.info("║ Connection Type: " + connectionType);
+                log.info("║ Record Type: " + recordName);
+                log.info("╠═══════════════════════════════════════════════════════════════════════════════");
+                log.info("║ JSON: " + jsonStr);
+                log.info("╚═══════════════════════════════════════════════════════════════════════════════");
```
Comment (thuva9872) [inline native/src/main/java/io/ballerina/stdlib/mi/BalExecutor.java]: Let's remove this debug log.

File: native/src/main/java/io/ballerina/stdlib/mi/BalExecutor.java [hunk 2]
```diff
@@ -502,10 +502,33 @@ private Object createRecordValue(String jsonString, String paramName, MessageCon
...
+                // Log the TYPED record to show defaults were applied
+                if (typedResult instanceof BMap) {
+                    String typedJson = ((io.ballerina.runtime.internal.values.MapValueImpl<?, ?>) typedResult).getJSONString();
+                    log.info("╔═══════════════════════════════════════════════════════════════════════════════");
+                    log.info("║ TYPED BALLERINA RECORD (after FromJsonStringWithType - defaults applied)");
+                    log.info("║ Record Type: " + recordName);
+                    log.info("╠═══════════════════════════════════════════════════════════════════════════════");
+                    log.info("║ Typed JSON: " + typedJson);
+                    log.info("╚═══════════════════════════════════════════════════════════════════════════════");
+                }
```
Comment (thuva9872) [inline native/src/main/java/io/ballerina/stdlib/mi/BalExecutor.java]: this is not needed. Let's keep the previous implementation.

File: tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java [hunk 3]
```diff
@@ -668,9 +668,12 @@ private static void writeJsonAttributeForFunctionParam(FunctionParam functionPar
                 if (jsonHelpTip == null || jsonHelpTip.isEmpty()) {
                     jsonHelpTip = "Expecting JSON object";
                 }
+                // Only apply regex validation for required fields - optional fields can be empty
+                String jsonValidateType = functionParam.isRequired() ? VALIDATE_TYPE_REGEX : "";
+                String jsonMatchPattern = functionParam.isRequired() ? JSON_OBJECT_REGEX : "";
```
Comment (thuva9872) [inline tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java]: don't we need to validate the optional fields?

File: tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java [hunk 4]
```diff
@@ -887,15 +899,26 @@ private static Combo getComboField(UnionFunctionParam unionFunctionParam, String
             unionJoiner.add("\"" + comboItem + "\"");
         }
         String unionComboValues = unionJoiner.toString();
-        FunctionParam firstMember = unionMembers.getFirst();
+        
+        // Only set default value for TOP-LEVEL combo fields (no enableCondition).
+        // For nested combos (inside another union member), use empty default to prevent
+        // MI Designer from saving unused defaults to XML when parent union is not selected.
```
Comment (thuva9872) [inline tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java]: If there is no default value, then will it not fail in the runtime?

File: tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java (hunk 3 above)
Comment (iamvirul) [reply tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java]: The current logic skips validation for optional fields to allow them to be left empty. However, you're right that if a user does provide a value, it should still be validated.

I can update the logic to use a regex pattern that allows either empty strings OR valid data Type for optional fields.

Comment (thuva9872) [reply tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java]: yeah, that is better. Let's update it

File: tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java (hunk 4 above)
Comment (iamvirul) [reply tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java]: No, it won't fail at runtime. The nested combo only becomes active/visible when its parent union member is selected (controlled by `enableCondition`). When the parent is selected, the user is required to choose a value in the UI before saving.

The empty default prevents the MI from pre-populating and saving unused combo values to XML when the parent union member is not selected - this avoids polluting the XML with default values that will never be used.

Comment (thuva9872) [reply tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java]: This will increase the complexity on the user side. We should use the default value to populate the fields.
If the parent union member is not selected, those fields are not shown in the UI. How is it getting added in the xml?

Comment (iamvirul) [reply tool-mi-module-gen-cli/src/main/java/io/ballerina/mi/ConnectorSerializer.java]: I've simplified this - now all combo fields (including nested ones) get the first member as default. The enableCondition controls visibility, so hidden fields won't be serialized to XML

File: tests/src/test/resources/expected/project7/uischema/postusersmessages_Importbyuserid.json [hunk 5]
```diff
@@ -50,9 +50,9 @@
                     "inputType": "stringOrExpression",
                     "defaultValue": "",
                     "required": "true",
-                    "helpTip": "",
-                    "validateType": "",
-                    "matchPattern": ""
+                    "helpTip": "Expecting JSON object",
+                    "validateType": "regex",
```
Comment (thuva9872) [inline tests/src/test/resources/expected/project7/uischema/postusersmessages_Importbyuserid.json]: can't we use `json` validate type?

File: tests/src/test/resources/expected/unionProject/uischema/processWithNil.json [hunk 6]
```diff
@@ -72,7 +72,7 @@
                     "required": "false",
                     "helpTip": "",
                     "validateType": "regex",
```
Comment (thuva9872) [inline tests/src/test/resources/expected/unionProject/uischema/processWithNil.json:74]: can't we use `number` validate type?

Comment (iamvirul) [reply tests/src/test/resources/expected/unionProject/uischema/processWithNil.json:74]: That regex validate empty or valid number, because that that attribute is `"required": "false"`

File: tests/src/test/resources/expected/project7/uischema/postusersmessages_Importbyuserid.json (hunk 5 above)
Comment (iamvirul) [reply tests/src/test/resources/expected/project7/uischema/postusersmessages_Importbyuserid.json]: yes we can. I'll update it

**Review by thuva9872 — APPROVED** [review]

**Review by daneshk — APPROVED** [review]
