### PR TITLE
Fix empty elements issue in generated UI Schema file

### LINKED ISSUE #4511: [Ballerina][MI] UI Schema Generation Missing Input Variables
### Description

When generating a UI schema using the `ballerina-mi-module-gen` tool for a Ballerina operation that accepts **multiple `xml` input parameters**, the resulting schema incorrectly produces an empty `"Input Variables"` attribute group. The tool fails to populate the parameter list, resulting in placeholder commas (`,,,`) instead of proper input attribute objects.

This prevents the UI from correctly displaying or configuring the operation inputs.

### Steps to Reproduce

1. Create a Ballerina module with the following function:

   ```ballerina
   @mi:Operation
   public function test(xml xmlA, xml xmlB, xml xmlC, xml xmlD) returns xml {
       return xml `<may22>${xmlA}${xmlB}${xmlC}${xmlD}</may22>`;
   }
   ```

2. Run the MI module generation tool:

   ```
     bal mi-module-gen -i <path-to-bal-file>
   ```

3. Open the generated UI schema JSON (usually under `uischema/` or generated into the connector metadata folder).

4. Navigate to:

   ```
   elements[0].value.elements[0].value.elements (Input Variables section)
   ```

---

## **Actual Result**

The `"Input Variables"` group contains **`,,,`** instead of generated entries:

```json
{
  "groupName": "Input Variables",
  "elements": [
    ,,,
  ]
}
```

No input fields are created for:

* `xmlA`
* `xmlB`
* `xmlC`
* `xmlD`

---

## **Expected Result**

The tool should generate **four properly-defined input attributes**, like:

```json
{
  "groupName": "Input Variables",
  "elements": [
    {
      "type": "attribute",
      "value": {
        "name": "xmlA",
        "displayName": "xmlA",
        "inputType": "stringOrExpression",
        "defaultValue": "",
        "required": "true",
        "helpTip": "Input parameters required to invoke the ballerina function"
      }
    },
    {
      "type": "attribute",
      "value": {
        "name": "xmlB",
        "displayName": "xmlB",
       "inputType": "stringOrExpression",
        "defaultValue": "",
        "required": "true",
        "helpTip": "Input parameters required to invoke the ballerina function"
      }
    },
    {
      "type": "attribute",
      "value": {
        "name": "xmlC",
        "displayName": "xmlC",
        "inputType": "stringOrExpression",
        "defaultValue": "",
        "required": "true",
        "helpTip": "Input parameters required to invoke the ballerina function"
      }
    },
    {
      "type": "attribute",
      "value": {
        "name": "xmlD",
        "displayName": "xmlD",
       "inputType": "stringOrExpression",
        "defaultValue": "",
        "required": "true",
        "helpTip": "Input parameters required to invoke the ballerina function"
      }
    }
  ]
}
```

---

### Version

latest

### Environment Details (with versions)

* **Operating System:** macOS 13.7.8 (22H730)
* **Machine:** MacBook Pro 15-inch (2017)
* **CPU:** Intel-based Mac
* **Ballerina Version:** 2201.12.10
* **MI Module Generator Tool:** `ballerina-mi-module-gen` (bundled with above version)
* **Java Version:** OpenJDK **21.0.9** (2025-10-21, LTS)
* **Build Method:** Command-line execution using:

  ```
  bal mi-module-gen -i
  ```
* **Project Type:** Ballerina integration connector using `@mi:Operation` annotations

### PR DESCRIPTION
**Pull request by daneshk**
## Purpose

Fixes: https://github.com/wso2/product-micro-integrator/issues/4511

## Goals

> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach

> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (
> email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature
> write-up is too long to paste here.

## User stories

> Summary of user stories addressed by this change>

## Release note

> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief
> explanation of why there’s no doc impact

## Training

> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification

> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct
> answer highlighted in bold), based on this change. Certification questions/answers should be sent to
> certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain
> why.

## Marketing

> Link to drafts of marketing content that will describe and promote this feature, including product page changes,
> technical articles, blog posts, videos, etc., if applicable

## Automation tests

- Unit tests
  > Code coverage information
- Integration tests
  > Details about the test cases and coverage

## Security checks

- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples

> Provide high-level details about the samples related to this feature

## Related PRs

> List any other related PRs

## Migrations (if applicable)

> Describe migration steps and platforms on which migration has been tested

## Test environment

> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested

## Learning

> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

### CODE REVIEW

File: tests/src/test/java/org/ballerina/test/ConnectorZipValidationTest.java [hunk 1]
```diff
@@ -141,7 +141,9 @@ public void testGeneratedConnectorArtifactsForProject(String projectName) throws
 
     private void compareFileContent(Path actualFilePath, Path expectedFilePath) throws IOException {
         String actualContent = new String(Files.readAllBytes(actualFilePath)).replaceAll("\\r\\n", "\n");
+        System.out.println("Actual Content:\n" + actualContent);
```
Comment (daneshk) [inline tests/src/test/java/org/ballerina/test/ConnectorZipValidationTest.java]:
```suggestion
```

File: tests/src/test/java/org/ballerina/test/ConnectorZipValidationTest.java [hunk 2]
```diff
@@ -141,7 +141,9 @@ public void testGeneratedConnectorArtifactsForProject(String projectName) throws
...
         String expectedContent = new String(Files.readAllBytes(expectedFilePath)).replaceAll("\\r\\n", "\n");
+        System.out.println("Expected Content:\n" + expectedContent);
```
Comment (daneshk) [inline tests/src/test/java/org/ballerina/test/ConnectorZipValidationTest.java]:
```suggestion
```

**Review by thuva9872 — APPROVED** [review]
